// Auto-generated by scripts/sync-frontend-addresses.js
// Run: node scripts/sync-frontend-addresses.js
export const CONTRACT_ADDRESSES = {
  VERIFIER:       "0x5FbDB2315678afecb367f032d93F642f64180aa3" as `0x${string}`,
  REGISTRY:       "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as `0x${string}`,
  ORDER_GATEWAY:  "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0" as `0x${string}`,
  ORDER_EXECUTOR: "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0" as `0x${string}`,
  TOKEN_IN:       "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9" as `0x${string}`,
  TOKEN_OUT:      "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9" as `0x${string}`,
} as const;
